apiVersion: apps/v1
kind: Deployment
metadata:
  name: a084110-backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: 416225317325.dkr.ecr.ap-northeast-2.amazonaws.com/a084110-backend:latest
        ports:
        - containerPort: 8080
        env:
        # [수정] 에러의 핵심인 URL 문법을 H2 표준 세미콜론(;)으로 바꿨습니다.
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:file:/app/data/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
        - name: SPRING_DATASOURCE_USERNAME
          value: "sa"
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "org.h2.Driver"
        # [추가] 로그에 떴던 USERS 테이블 에러를 막는 핵심 옵션
        - name: SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION
          value: "true"
        - name: SPRING_SQL_INIT_MODE
          value: "always"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"