apiVersion: apps/v1
kind: Deployment
metadata:
  name: a084110-backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: 416225317325.dkr.ecr.ap-northeast-2.amazonaws.com/a084110-backend:latest
        ports:
        - containerPort: 8080
        env:
        # 1. 수정된 H2 접속 주소 (인메모리 방식)
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
        
        # 2. H2 기본 계정 정보
        - name: SPRING_DATASOURCE_USERNAME
          value: "sa"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "" 

        # 3. H2 드라이버 명시
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "org.h2.Driver"

        # 4. H2 전용 문법(Dialect) 설정
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.H2Dialect"
        
        # 5. 테이블 자동 생성 및 H2 콘솔 활성화
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_H2_CONSOLE_ENABLED
          value: "true"
        - name: SPRING_H2_CONSOLE_PATH
          value: "/h2-console"