apiVersion: apps/v1
kind: Deployment
metadata:
  name: a084110-frontend
  labels:
    app: a084110-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: a084110-frontend
  template:
    metadata:
      labels:
        app: a084110-frontend
    spec:
      containers:
      - name: frontend
        # 빌드된 최신 이미지를 가져옵니다.
        image: 416225317325.dkr.ecr.ap-northeast-2.amazonaws.com/a084110-frontend:latest
        ports:
        - containerPort: 80
        # 컨테이너가 항상 최신 이미지를 받아오도록 설정
        imagePullPolicy: Always