spring:
  h2:
    console:
      enabled: true           # 웹에서 DB를 확인할 수 있게 콘솔 활성화
      path: /h2-console       # 주소: 백엔드주소/h2-console

  datasource:
    # [수정] 에러가 났던 복잡한 옵션들을 제거하고 표준 세미콜론(;) 방식으로 변경했습니다.
    # 인메모리 방식: 서버 재시작 시 데이터 초기화
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update        # 엔티티를 보고 테이블을 자동 생성
    show-sql: true            # 실행되는 쿼리를 로그로 확인
    properties:
      hibernate:
        format_sql: true

app:
  api-url: ${API_URL:http://localhost:8080}  # 필요 시 백엔드 ELB 주소
  cors:
    allowed-origins: http://k8s-default-a084110f-669abede59-50dcce7293374d93.elb.ap-northeast-2.amazonaws.com